# -*- coding: utf-8 -*-
"""Assignment_1_ Array_Linked_List_Stack_Queues.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uwn3l10Bfp63xEofADgHBTN8DK_gF83M
"""

#Array

array = [1,2,3,4,5,6,7,8,9,10]
print(array)

#access an element
firstElement = array[0]
print(firstElement)

def insertNext(array):
  number = 11
  index = 10
  array.insert(index, number)
  print(array)

insertNext(array)

def deleteNext(array):
  del array[10]
  print(array)

deleteNext(array)

#References
#https://www.askpython.com/python/array/python-add-elements-to-an-array
#https://stackabuse.com/remove-element-from-an-array-in-python/

#Linked List

class MyNode:
    def __init__(self, x):
        self.data = x
        self.next = None

#define linkedlist
class MyLinkedList:
  def __init__(self):
    self.start = None

#add an item
  def insert(self, x):
    node_x = MyNode(x)
    #node_x.data = x
    node_x.next_node = self.start
    self.start = node_x

#Traversing over the Linked List
  def traverse(self):
    ptr = self.start
    while ptr != None:
      print(ptr.data)
      ptr = ptr.next_node

#removing from list
  def delete(self):
    if self.start.next_node != None:
      self.start = self.start.next_node
    else:
      raise Exception("Your List is already empty.")

myList = MyLinkedList()

myList.insert(1)
myList.insert(2)
myList.insert(3)
myList.delete()
myList.start.data
myList.traverse()

#Stack

stack_example = list()
print(stack_example)

def insertNum(stack_example):
  stack_example.append(1)
  stack_example.append(2)
  stack_example.append(3)
  stack_example.append(4)
  print(stack_example)

insertNum(stack_example)

def deleteNum(stack_example):
  stack_example.pop()
  stack_example.pop()
  stack_example.pop()
  print(stack_example)

deleteNum(stack_example)

#References
#https://www.geeksforgeeks.org/stack-in-python/

#Queue

import queue
q = queue.Queue()
sample = [1, 2, 3, 4, 5]

#add
for num in sample:
  q.put(num)

#remove
print(q.get())
print(q.get())
print(q.get())
print(q.get())
print(q.get())

#References
#https://www.geeksforgeeks.org/queue-in-python/